propertyPrueba:
  test: developmentDepartmentMs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.microservices.resilience4j.department_ms: DEBUG
