spring:
  data:
    mongodb:
      uri: mongodb://admin:password123@localhost:27017/employee_db?authSource=admin

server:
  port: 40070
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.microservices.resilience4j.employee_ms: DEBUG